init:
  - git config --global core.autocrlf input

version: '{build}'

environment:
  matrix:
    - nodejs_version: '0.10'

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install

build_script:
  - '"C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall"'

test_script:
  - ps: 'node test\\test.js # PowerShell'
  - cmd: node test\test.js
